dependencies:
  - conda-forge::numpy=1.19.2
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9
  - pip:
      - matplotlib==3.4.3
      - pulp==2.7.0
      - astropy==5.1
      - scikit-learn==1.3.2
      - tqdm==4.66.4
      - scipy==1.24.3
